version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mcrouter
    mcrouter:
        image: itzg/mc-router
        environment:
            # enable API
            API_BINDING: ":25564"
        ports:
            - 25565:25565
            # bind the API port to only loopback to avoid external exposure
            - 127.0.0.1:25564:25564
        command: --mapping=vanilla.example.com=vanilla:25565,forge.example.com=forge:25565
        networks:
            - sail
networks:
    sail:
        driver: bridge
